import '../styles/globals.css';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Devter 🐦 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <section className='main-section'>
          <Component {...pageProps} />
        </section>
      </main>
    </>
  )
}

export default MyApp
